# Generated by Django 5.0.3 on 2024-05-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sage', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('surl', models.URLField()),
                ('spassword', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('hubby', models.CharField(max_length=100)),
                ('school_type', models.CharField(max_length=50)),
                ('school_logo', models.FileField(upload_to='logos/')),
            ],
        ),
    ]
